# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  project: htmlArea RTE
  version: 6.2
  release: 6.2
  intersphinx_mapping:
    t3tca:
    - http://docs.typo3.org/typo3cms/TCAReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference/
    - null
...
